apiVersion: v1
kind: Service
metadata:
  name: sw-service
spec:
  selector:
    app: {{ .Values.name }}
  type: LoadBalancer 
  ports:
    - protocol: TCP
      port: {{ .Values.deployment.port }}
      targetPort: {{ .Values.deployment.port }}
      nodePort: 31000